---
name: Generate Images

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:
  conversion:
    name: Generate Images
    runs-on: ubuntu-latest
    container:
      image: linuxserver/inkscape:1.3.2
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
            apk --no-cache add imagemagick
            apk --no-cache add exiftool

      - name: convert images
        run: |
            ./conversion-script.sh

      - name: package images
        shell: bash
        run: |
            # The tar is required to preserve symlinks
            tar cvf device-pictures-jpg.tar README.md pictures-jpg/
            tar cvf device-pictures-png.tar README.md pictures-png/

      - name: upload JPG archive
        uses: actions/upload-artifact@v4
        with:
          name: device-pictures-jpg.tar
          if-no-files-found: error
          path: device-pictures-jpg.tar

      - name: upload PNG archive
        uses: actions/upload-artifact@v4
        with:
          name: device-pictures-png.tar
          if-no-files-found: error
          path: device-pictures-png.tar
